### PR TITLE
LPS-143170

### PR DESCRIPTION
**Pull request by javalosjr96**
@fortunatomaldonado 
Hi Fortunato,
I created a PTR ticket it was determined that this is an appropriate solution:
https://issues.liferay.com/browse/PTR-2759

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @javalosjr96,

This fix looks good and will be forwarding it to the staging team.

**Comment by javalosjr96** [comment]
@fortunatomaldonado 
Thank you for reviewing this.

**Pull request closed without merging**
