### PR TITLE
LPP-47516

### PR DESCRIPTION
**Pull request by SelenaAungst**
Temporary fix for [LPP-47516](https://issues.liferay.com/browse/LPP-47516)

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
LGTM!

Did they answer if they wanted to include this in master or wait for another fix?

**Comment by SelenaAungst** [comment]
Thanks for reviewing this! We are waiting on another fix to be made, this is just temporary

**Pull request closed without merging**
