### PR TITLE
LPS-153717

### PR DESCRIPTION
**Pull request by SelenaAungst**
LPS-153717 Added title, added cancel button, and relocated buttons to make Mail Settings page visually consistent with other Email settings pages.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @SelenaAungst,

When testing the Cancel button, the page stays on the Email Setting page rather than redirecting back to the Instance Setting page, like the other Cancel buttons.
Can you take a look at this and see why it is not being redirected?

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
> Hello @SelenaAungst,
> 
> When testing the Cancel button, the page stays on the Email Setting page rather than redirecting back to the Instance Setting page, like the other Cancel buttons. Can you take a look at this and see why it is not being redirected?

Hi @fortunatomaldonado,
I added the correct redirect link to the cancel button. Let me know if there is anything else I can do!

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Looks good forward: https://github.com/liferay-usm/liferay-portal/pull/609

**Pull request closed without merging**
