### PR TITLE
LPS-156119

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-156119](https://issues.liferay.com/browse/LPS-156119) Enabled save button, added warning toast when saving without a name, added required asterisk, and added new Language Key.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
I apologize for closing this earlier, I misread the expected and actual behavior.
I have sent pr here: https://github.com/liferay-frontend/liferay-portal/pull/2506

**Pull request closed without merging**
