### PR TITLE
LPS-162027

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-162027](https://issues.liferay.com/browse/LPS-162027) Added the required field attribute to the content editor for KB articles. Here I followed the structure of other components that have editor content required (like Blog entries) and added the required field to the editor instead of adding an asterisk.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
This pull is good to go; there's no need to send it to us (liferay-lima). @fortunatomaldonado if you're ok with the changes, you can forward it yourself.

**Comment by fortunatomaldonado** [comment]
Hello @SelenaAungst,
Nice fix!
In my testing, the Content does not have an asterisk. Pushing the Publish button makes the error message appear.
Were you able to see the asterisk?

@adolfopa, is there anything missing for the asterisk to show?

Thank you both!

**Comment by SelenaAungst** [comment]
Hi @fortunatomaldonado,
This is the correct behavior. I found another component that has required content (in this case Blog entries) and used the same method of making the editor content required for KB articles to keep things consistent. There should just be an error message underneath content if you attempt to publish while it is empty, but no asterisk. 

Let me know if any changes need to be made for this @fortunatomaldonado @adolfopa. Thank you!

**Comment by fortunatomaldonado** [comment]
@SelenaAungst, if this is the case, then we should change the expected behavior on the LPS or else QA will not pass the ticket.
I will go ahead and forward the fix.

Thanks !

**Comment by fortunatomaldonado** [comment]
FWD: https://github.com/brianchandotcom/liferay-portal/pull/122823

**Comment by ambrinchaudhary** [comment]
Hey all, I just found this pull while reviewing https://issues.liferay.com/browse/LPS-162923, Just wanted to let you know the [pull](https://github.com/liferay-frontend/liferay-portal/pull/2716) I've just sent to Frontend Infra team to show the asterisk.

**Pull request closed without merging**
