### PR TITLE
LPS-171421

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-171421](https://issues.liferay.com/browse/LPS-171421) Added aria-label for SR to read draft status on pages.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @SelenaAungst,

I found the screen reader never reads the title of the page. Do you get the same result?

**Comment by SelenaAungst** [comment]
Hi @fortunatomaldonado, I sent a new PR for this here: https://github.com/fortunatomaldonado/liferay-portal/pull/73

**Pull request closed without merging**
