### PR TITLE
LPS-156741

### PR DESCRIPTION
**Pull request by SelenaAungst**
[ LPS-156741](https://issues.liferay.com/browse/LPS-156741) Increased spacing between save and cancel buttons, and decreased spacing between checkboxes and help text.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
Hi @fortunatomaldonado,
I added the changes you requested. Please let me know if there is anything else needed for this.

**Comment by fortunatomaldonado** [comment]
LGTM! FWD: https://github.com/liferay-usm/liferay-portal/pull/730

**Pull request closed without merging**
