### PR TITLE
LPS-161242

### PR DESCRIPTION
**Pull request by SelenaAungst**
[ LPS-161242](https://issues.liferay.com/browse/LPS-161242) Corrected spacing between icons and link titles.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
LGTM! FWD: https://github.com/liferay-forms/liferay-portal/pull/1950

**Pull request closed without merging**
