### PR TITLE
LPS-170258

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-170258](https://issues.liferay.com/browse/LPS-170258) Added aria-labels to combo boxes. I just used the same language keys as the titles, please let me know if this needs to be changed.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:stop

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello Selena, can you rebase the fix to the latest master and resend the PR?

Thank you!

**Comment by SelenaAungst** [comment]
@fortunatomaldonado I sent a new PR for this here: https://github.com/fortunatomaldonado/liferay-portal/pull/66

**Pull request closed without merging**
