### PR TITLE
LPS-161381

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-161381](https://issues.liferay.com/browse/LPS-161380) Added button outline borderless and secondary classes to cancel button.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
LGTM! FWD: https://github.com/liferay-usm/liferay-portal/pull/730

**Comment by fortunatomaldonado** [comment]
LGTM ! https://github.com/liferay-echo/liferay-portal/pull/9613

**Pull request closed without merging**
