### PR TITLE
LPS-162441

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-162441](https://issues.liferay.com/browse/LPS-162441) Added role=navigation and aria-label=Main Navigation to the navigation menu div.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @SelenaAungst,

When testing, the home page does not work and I was able to find errors in the logs. 
I believe that this issue has a lot of dependencies in the .ftl files.
Can you take a look at this and see if you get the same results?

**Comment by SelenaAungst** [comment]
Hi @fortunatomaldonado, 
I tested this on U41 and was able to see the labels on the home page with no errors. What errors did you see for this?

**Comment by fortunatomaldonado** [comment]
Hello @SelenaAungst,

I tested on 6bbb05ace30be14795004ee850c12523ee86e9d4 and got the following error.
Can you test to see if you get the same result?

Thank you!

https://gist.github.com/fortunatomaldonado/a4346fa5d392cc9b8c852548ecd77753

**Comment by victorg1991** [comment]
hey @SelenaAungst I believe we probably should include the role and the aria label in the navigation menu right? not in the control menu

**Comment by SelenaAungst** [comment]
Hi @victorg1991,
Thanks for pointing this out! After clarifying with @fortunatomaldonado it looks like this issue will not be fixed as that menu already has the role of menubar.

**Pull request closed without merging**
