### PR TITLE
LPS-164443

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-164443](https://issues.liferay.com/browse/LPS-164443) Updated z-index for simple menus in the Calendar widget.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
LGTM! FWD: https://github.com/liferay-workflow/liferay-portal/pull/836

**Pull request closed without merging**
