### PR TITLE
LPS-162123

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-162123](https://issues.liferay.com/browse/LPS-162123) Corrected language key translation.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
FWD: https://github.com/liferay-echo/liferay-portal/pull/10031

**Pull request closed without merging**
