### PR TITLE
LPS-156317

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-156317](https://issues.liferay.com/browse/LPS-156317) Added space between buttons and above toggle to correct lack of spacing.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @SelenaAungst,

I apologize for the long wait on these PRs. It looks like the issue has already been fixed. 
Take a look at the commits. https://issues.liferay.com/browse/LPS-156317?devStatusDetailDialog=repository
For future issues as this, make sure to use bootstrap spacing: https://getbootstrap.com/docs/4.0/utilities/spacing/

Again sorry for the long wait on this.

**Pull request closed without merging**
