### PR TITLE
LPS-152924

### PR DESCRIPTION
**Pull request by SelenaAungst**
LPS-152924 Moved description above info message and edited padding/margins. Adjusted some padding/margins to make sure spacing looks even on all settings pages.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @SelenaAungst, it looks like the the title of Session Property Vocabularies is still `Add` and not `Add Session Property Vocabulary`.
When you have time, can you double check this?

Thank you.

**Comment by SelenaAungst** [comment]
> Hello @SelenaAungst, it looks like the the title of Session Property Vocabularies is still `Add` and not `Add Session Property Vocabulary`. When you have time, can you double check this?
> 
> Thank you.

After some discussion on [LPS-152924](https://issues.liferay.com/browse/LPS-152924), it was determined that the title should stay as `Add` to remain consistent with similar pages, and because there is no way to directly change this title only for this page. There would need to be a restructuring of these pages to allow for this and other teams would need to be involved, so we settled on just fixing the spacing and alignment issues for this ticket. Hope that clears things up!

**Comment by fortunatomaldonado** [comment]
Looks good! Forward: https://github.com/liferay-usm/liferay-portal/pull/612

**Pull request closed without merging**
