### PR TITLE
LPS-166594

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-166594](https://issues.liferay.com/browse/LPS-166594) Added aria-label to options button.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
LGTM! FWD: https://github.com/liferay-echo/liferay-portal/pull/10053

**Pull request closed without merging**
