### PR TITLE
Lps 144421

### PR DESCRIPTION
**Pull request by javalosjr96**

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @javalosjr96,
Looking at your change `background-size: auto;`, it looks like it adds more cropping to some of the images as we can see in the video.
Do we know the expected behavior of the images? Do we want the images to not be cropped at all, width or length? If we don't know the answer to this we can try asking in the t-lima channel to get better understanding of what is expected.
Let me know if I am misunderstanding things here.
Thank you!

https://user-images.githubusercontent.com/31672551/147291249-0dfc6f85-2a53-4daa-9ab7-6509ea30d709.mp4

**Comment by javalosjr96** [comment]
@fortunatomaldonado It differs with different images.  I had a hard time trying to find what was wrong and the customer stated that it needed to be set to auto so that the proportions are maintained.  The original state was set to cover.

**Comment by javalosjr96** [comment]
@fortunatomaldonado 
We can open a PTR, but I think the answer would be whichever option gives the best look for any image posted.

**Comment by javalosjr96** [comment]
image-out-of-proportion
Here's an example of an image that is cropped incorrectly and fixed with the setting set to auto.

**Comment by fortunatomaldonado** [comment]
Hello @javalosjr96,

I am hesitate to move forward with this since changing this behavior may result in other customers preferring the previous behavior and wanting to change it back.
From my perspective, the best way to go about this is having the customer change this behavior in their custom CSS theme. This way the customer can have their desired behavior without changing the behavior for everyone else. 
I am thinking this way since it will be hard to please everyone and I do not believe there is a right solution for everyone.

Let me know what you think about this and if we want to get a final decision we can always open a PTR like you said.

**Comment by javalosjr96** [comment]
@fortunatomaldonado 
I agree.  This issue felt very specific to this client since I failed to get it to reproduce until I selected the correct image with the specifications that causes this "bug".  I don't think a PTR will need to be open since you gave a straightforward solution for the customer,  I'll relay the information and see if I get an push back.  I'll close this PR, hopefully close the ticket if the customer accepts the proposed solution.   Thank you for your input.

**Pull request closed without merging**
