### PR TITLE
LPS-154907

### PR DESCRIPTION
**Pull request by SelenaAungst**
LPS-154907 Added staging label to staging version of sites in Asset Libraries connected sites list. This allows for both the staging and live versions of the site to show up as connected sites while being able to tell the versions apart visually.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
I realized I made a typo! Re-testing now.

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
@fortunatomaldonado 
I made the changes you suggested, testing them now!

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Forward fix https://github.com/liferay-echo/liferay-portal/pull/8362

**Pull request closed without merging**
