### PR TITLE
LPS-159738

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-159738](https://issues.liferay.com/browse/LPS-159738) Added empty alt attribute for accessibility.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
FWD: https://github.com/liferay-echo/liferay-portal/pull/9327

**Pull request closed without merging**
