### PR TITLE
[TS] LPS-158192

### PR DESCRIPTION
**Pull request by jonathanmccann**
@fortunatomaldonado This resolves an issue where a button is only displayed when the user hovers over it but when utilizing keyboard navigation the button never appears.

**Steps to Reproduce**

1. Click on user icon in upper right - My Profile
2. Hover over the Profile widget so that the edit button appears
3. Type the tab key until a small highlighted area above Test Test appears within the Profile widget. This is the edit button but the button itself does not appear when tabbing through the elements.

**Changes**

The first commit makes it so that when the element is in focus then it will be shown.

The second commit floats the `span` that contains the button to the right. When the browser highlights the element when tabbing through the highlight in on the left side of the widget while the button is on the right. This additional CSS allows the highlight to appear where the button is.

Please let me know your thoughts on these changes and if there is a better way to achieve the result the client desires.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
Hello @jonathanmccann,

The first commit looks good! 

In chrome, the float-right seems to move the alignment of the other content when tabbing through. I think we should try to find another way to go about moving the highlight.
Also there is no highlight box while using chorme. I believe I see it in firefox but it also looks odd there too.

Let me know if you are able to see the same results and we can discuss on how to go about fixing this.

**Comment by jonathanmccann** [comment]
Thank you for catching that. We can drop the second commit since the original issue was the pencil icon not appearing. Let me know what you think about that.

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
FWD: https://github.com/brianchandotcom/liferay-portal/pull/120401

**Pull request closed without merging**
