### PR TITLE
LPS-163989

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-163989](https://issues.liferay.com/browse/LPS-163989) Added missing classes to permission nav item.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
LGTM! FWD: https://github.com/liferay-usm/liferay-portal/pull/802

**Pull request closed without merging**
