### PR TITLE
LPS-175354

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-175354](https://issues.liferay.com/browse/LPS-175354) Modified InvalidContentMessage to display when a non-XML file is selected for import, and allowed for special characters to be encoded before decoding is attempted.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Started Reviewing

**Comment by fortunatomaldonado** [comment]
LGTM FWD: https://github.com/liferay-workflow/liferay-portal/pull/897

**Pull request closed without merging**
