### PR TITLE
LPS-154118

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-154118](https://issues.liferay.com/browse/LPS-154118) Added extra space above content on applicable tabs and relocated buttons where necessary to make all Server Administration tabs consistent in layout.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @SelenaAungst,
This looks good! I am waiting to push until https://issues.liferay.com/browse/LPS-153717 is committed since there are changes in the same files. I will handle the updates when it is pushed.

**Comment by SelenaAungst** [comment]
> Hello @SelenaAungst, This looks good! I am waiting to push until https://issues.liferay.com/browse/LPS-153717 is committed since there are changes in the same files. I will handle the updates when it is pushed.

Hi @fortunatomaldonado! It looks like [LPS-153717](https://issues.liferay.com/browse/LPS-153717) has been committed in [this PR](https://github.com/brianchandotcom/liferay-portal/pull/119260). Please let me know if there is anything else I can do for this. Thank you!

**Comment by fortunatomaldonado** [comment]
Forward: https://github.com/liferay-usm/liferay-portal/pull/639

**Pull request closed without merging**
