### PR TITLE
LPS-158973

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPS-158973](https://issues.liferay.com/browse/LPS-158973) Added z-index value for CKEditor dropdown menus to prevent them from appearing above all other elements on page when scrolling.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @SelenaAungst,

I found that all the CSS in _editor_ckeditor.scss was moved over to modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/css/main.scss
When you have a chance, can you add your changes there?

Thank you!

**Comment by SelenaAungst** [comment]
Hi @fortunatomaldonado,

I moved my changes to `modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/css/main.scss` as requested. Additionally, I removed the changes from the file they were previously in and it is now empty. I believe the file was empty before I added my changes so I did not delete it, but please let me know if I should do so. 

Thank you!

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:stop

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
FWD: https://github.com/liferay-frontend/liferay-portal/pull/2585

**Pull request closed without merging**
