### PR TITLE
LPS-158192 - if one of the control menu areas has only one item, remove the semantics of it being a list

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPP-46636

Hi @fortunatomaldonado,

This is technically yet another one of the accessibility issues thus why I'm sending it to you. Essentially, due to the way that the control menu is internally structured, technically the bar is actually a menu with three separate submenus (there's a picture on https://issues.liferay.com/browse/LPP-46636 that should help illustrate what I'm talking about) and not just one large header. Due to this, the screen reader (correctly) reads the semantics as a list with three items (the three submenus) -> list with one item (since in a default instance the first submenu only has one item which is the link to the product menu) -> the product menu link . However, the client finds this confusing. As a compromise, I'm changing the logic slightly to add a check for the size of the list per a suggestion made in [PTR-3328](https://issues.liferay.com/browse/PTR-3328). If there's only one item, the role for the second list is changed to presentation to remove its semantics. I've made the other role to be explicitly 'menu' since it's technically a menu, but let me know if you feel like that's inappropriate for the role. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Looks like I somehow accidentally added a line break at the very top of the file which could explain the SF issues. Force pushed a fix and I'll restart the test suite.

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
LGTM! FWD: https://github.com/brianchandotcom/liferay-portal/pull/123968

**Pull request closed without merging**
